### ISSUE TITLE
Is this project being maintained?

### ISSUE THREAD

**Issue by chiefy** [segmentio/metalsmith-metadata#15]
cc: @ianstormtaylor 
I just started using metalsmith (and I really like it), but it seems like some of the plugins aren't being  maintained.  Do you guys need any help? Seems like people using this are running into some of the same issues I did.

**Comment by lambtron** [comment]
This was just brought to my attention that this project (and many other plugins unfortunately) weren't getting the love that they deserved. I'll take some time to go through them.

If you want to help, absolutely!! Feel free to join the [Slack room](http://metalsmith-slack.herokuapp.com) and ping me or leave a message in any of the channels, as well :)

**Comment by chiefy** [comment]
thanks @lambtron !

**Comment by wernerglinka** [comment]
Metalsmith is open for business again. After a long tome of inactivity we are working to revitalize the project. Join the Gitter group to learn more: https://gitter.im/metalsmith/community

**Comment by wernerglinka** [comment]
Metalsmith is open for business again. After a long tome of inactivity we are working to revitalize the project. Join the Gitter group to learn more: https://gitter.im/metalsmith/community
